#Name: Sidney Jackson
#Comments: file created to configure routing for the client VM

network:
 version: 2
 renderer: networkd
 ethernets:
  enp0s3:
   dhcp4: no
   addresses:
    - 10.0.0.10/8
   gateway4: 10.0.0.100
   nameservers:
    addresses: [8.8.8.8, 8.8.4.4]
